{% set name = "HyperTS" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DataCanvasIO/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 471cf62a64f72e2e14fc48df1aee3a6641a546e037323ec8731bad10de01687c

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - hypernets >=0.3.0
    - prophet >=1.0.1
    - statsmodels >=0.12.1
    - numpy >=1.16.5
    - pandas >=0.25.3, <2.0
    - scikit-learn >=0.22.1
    # - scipy <1.8.0 # remove this line when the issue is fixed. https://github.com/conda-forge/sktime-feedstock/issues/31
    - scipy
    - numba
  run_constrained:
    - tensorflow >=2.0, <=2.10
    - arviz <=0.12.1

test:
  imports:
    - hyperts
    - hyperts.tests
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/DataCanvasIO/HyperTS
  license: Apache-2.0
  license_file: LICENSE
  summary: A Full-Pipeline AutoML&AutoDL Toolkit about Time Series.
  description: |
    HyperTS is a Python package that provides an end-to-end time series (TS) analysis toolkit. 
    It covers complete and flexible AutoML workflows for TS, including data clearning, preprocessing, feature engineering, model selection, hyperparamter optimization, result evaluation, and visualization.
  doc_url: https://hyperts.readthedocs.io/
  dev_url: https://github.com/DataCanvasIO/HyperTS

extra:
  recipe-maintainers:
    - oaksharks
